namespaceOverride: monito

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: "7d"
    enableAdminAPI: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeInterval: "30s"
    resources:
      requests:
        memory: "400Mi"

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

grafana:
  enabled: true

# Disable excessive default rules and monitors to control annotation size
defaultRules:
  create: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
